# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

  

development:
  secret_key_base: 02d08bf712909dfe9c2412ceadf1f19ee55e822d8a78f1e354c8b4da277c1e000c6ac47062142b8078423d4b39ab3cb7534ecbdac7439ab4cb5e7a36f87dbc54
  paypal_host: https://www.sandbox.paypal.com
  #app_host:  https://816a4dd6.ngrok.io
  app_host:   https://212eb64b.ngrok.io
 
  
  
test:
  secret_key_base: 61d615d6386f394c16832656bd7d54f2e94d36eeff8288dd99b2372c237c75b58352de52aab2aedc38f7585cfb128af5e1b070d9d4a6c55a659b557cf65c4a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: http://guarded-dawn-1242.herokuapp.com
  #app_host: http://www.gotealeaf.com/
